
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "breathe_easy"
version = "2.0.0"
requires-python = ">=3.9"
dependencies = [
    "PyYAML",
    "ruamel.yaml"
]
authors = [{ name = "BChap - SleepHQ Community Member" }]

[project.scripts]
breathe_easy = "breathe_easy.breathe_easy:main"

[tool.setuptools.packages.find]
where = ["."]
include = ["breathe_easy*"]
